"""Add beneficiary relationship to story

Revision ID: 244899bf6589
Revises: 9a03d8abd7c8
Create Date: 2025-07-31 22:14:31.835939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244899bf6589'
down_revision = '9a03d8abd7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_story_beneficiary_id', 'beneficiary', ['beneficiary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint('fk_story_beneficiary_id', type_='foreignkey')
        batch_op.drop_column('beneficiary_id')

    # ### end Alembic commands ###
